import type { Metadata } from "next";
import "./globals.css";
import Canonical from "@/components/canonical"
import { fetchData } from "./websitesettings";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let websiteDetails = null;

  try {
    websiteDetails = await fetchData();
  } catch (error) {
    console.error("Failed to fetch website details:", error);
  }  return (
    <html lang="en">
      <head>
      <Canonical />
      <link rel="icon" href={`http://192.168.211.32:8000${websiteDetails?.favicon}`} />
      <link rel="apple-touch-icon" href={`http://192.168.211.32:8000${websiteDetails?.favicon}`} />
      </head>
      <body  
      suppressHydrationWarning={true}
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
